### ISSUE TITLE
zst compression not supported on Debian based systems

### ISSUE THREAD

**Issue by glitch59** [schorschii/nemo-extensions#2]
Hi, 

First of all, thanks for the work creating these packages, it is very appreciated!

Secondly, regarding the new release I get stuck on the following issue:

The .deb files are created with zst compression:

```
root@dev101:/usr/local/src/nemo/deb# file *
control.tar.zst:                 Zstandard compressed data (v0.8+), Dictionary ID: None
data.tar.zst:                    Zstandard compressed data (v0.8+), Dictionary ID: None
Nemo-Action-Compress-Images.deb: Debian binary package (format 2.0), with control.tar.zs, data compression zst
Nemo-Action-Compress-PDF.deb:    Debian binary package (format 2.0), with control.tar.zs, data compression zst
Nemo-Action-Convert-MSG.deb:     Debian binary package (format 2.0), with control.tar.zs, data compression zst
Nemo-Action-DaVinci-Audio.deb:   Debian binary package (format 2.0), with control.tar.zs, data compression zst
Nemo-Action-Send-By-Email.deb:   Debian binary package (format 2.0), with control.tar.zs, data compression zst

```
But this .zst compression is not supported on Debian / Ubuntu systems.
When installing this results in the following error:

```
root@dev101:/usr/local/src/nemo/deb# dpkg -i Nemo-Action-Compress-Images.deb
dpkg-deb: error: archive 'Nemo-Action-Compress-Images.deb' uses unknown compression for member 'control.tar.zst', giving up
dpkg: error processing archive Nemo-Action-Compress-Images.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 Nemo-Action-Compress-Images.deb

```
Can it be changed to tar.gz for example?

Many thanks!

**Comment by schorschii** [comment]
I created this packages on Linux Mint 21 (Ubuntu 22.04) and also tested them successfully on Mint 20 (Ubuntu 20.04). But you are right, they do not install on Debian. It seems that since Ubuntu 22.04, `dpkg-deb --build` uses zst compression as default. My previous packages were built on Mint 20 and here the default compression was xz. I'll keep this compression method for my packages by adding `-Zxz` to the build command.

You can download the xz compressed packages now, I replaced them in the latest release.

Thanks for your feedback, this is also important for my other projects. I didn't thought of that Ubuntu's and Debian's dpkg could be different when it comes to compression algorithm support.
